version: '2'
services:
  kong-db:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    

  kong:
    image: kong
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    expose:
      - 7946
      - 7946/udp
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=langukinfrastructure_kong-db_1.langukinfrastructure_default
    depends_on:
      - kong-db