version: '2'

services:
  root:
    build: ./nginx
    restart: always
    ports:
      - '80:80'
    networks:
      - services
  ner-ms-uk:
    image: chaliy/ner-ms:uk
    restart: always
    expose:
      - '8080'
    networks:
      - services
  ner-ms-en:
    image: chaliy/ner-ms:en
    restart: always
    expose:
      - '8080'
    networks:
      - services
  ner-ms-ru:
    image: chaliy/ner-ms:ru
    restart: always
    expose:
      - '8080'
    networks:
      - services
  wiki-lang-detect:
    image: chaliy/wiki-lang-detect
    restart: always
    expose:
      - '5000'
    networks:
      - services
  api_nlp_uk:
    image: chaliy/api_nlp_uk
    restart: always
    expose:
      - '8080'
    networks:
      - services

networks:
  services: