version: '2'

services:
  root:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    links:
    - ner-ms-uk
    - ner-ms-en
    - ner-ms-ru
    - wiki-lang-detect
    - api_nlp_uk
  ner-ms-uk:
    image: chaliy/ner-ms:uk
    restart: always
    ports:
      - '8080'
  ner-ms-en:
    image: chaliy/ner-ms:en
    restart: always
    ports:
      - '8080'
  ner-ms-ru:
    image: chaliy/ner-ms:ru
    restart: always
    ports:
      - '8080'
  wiki-lang-detect:
    image: chaliy/wiki-lang-detect
    restart: always
    ports:
      - '5000'
  api_nlp_uk:
    image: chaliy/api_nlp_uk
    restart: always
    ports:
      - '8080'
